services:
  - type: web
    name: mnist-web-app
    env: python
    buildCommand: apt-get update && apt-get install -y build-essential python3-dev && pip install --upgrade pip wheel setuptools && pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn mnist_web.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: MNIST_PRELOAD_DATA
        value: 1 